config/routes.rb
JoobsboxRails::Application.routes.draw do

 

  devise_for :users, :controllers => {:sessions => 'sessions'}

  namespace :admin do  
    match '' => 'home#index'
    resources :categories, :postings, :settings , :themes , :plugins , :roles , :users ,
              :group_permissions 
    resources :groups do
      member do
        get "users"
        post "add_users"
        post "remove_users"
      end
    end
  end

  match 'publish' => 'jobs#new'
  match 'post' => 'resumes#new'
  match 'search' => 'search#index'
  match 'google_images' => 'search#google_images'
  match 'profiles' => 'search#search'
  match ':user_id/profile/:id' => 'resumes#profile' , :as => :profile
  resources :jobs do
    member do
       get 'applied_resumes'
    end
    collection do
      get 'my_postings'     
    end
  end
  resources :resumes do
    member do
      get 'apply'
      get 'download'
    end
    collection do
      post 'submit_profile'
    end
  end
  resources :categories

  root :to => 'home#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @jobs = Job.search do
      keywords params[:jobq]

      with(:is_approved , true)
      with(:expiration_date).greater_than Time.now
      order_by :created_at, :desc
      paginate :page => params[:page] || 1, :per_page => 15
     
    end  
    @jobs = @jobs.results
  end



  def search
      @resumes = Resume.search do
      keywords params[:resumeq]
      without(:user_id, current_user.id)
      order_by :created_at, :desc
      paginate :page => params[:page] || 1, :per_page => 15

    end
    @resumes = @resumes.results
  end


  def google_images
    params[:start] = params[:start].to_i
    @page_title = "Import image from Google"
    @google_images = GoogleImage.all(params[:keywords], params[:start])
  end
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_default_index.html.erb
<div class="inner">
  <a href="#">Search : <%= params[:jobq] %></a>
</div>
<% if @jobs.total > 0 %>
<ul>
  <% @jobs.each_with_index do |job , i |%>
    <li <% if i%2 == 0 %> class="alternate"<% end%>  >
      <strong><%= job.location %> :</strong>
      <a href="<%=job_path(job)%>"><%= job.title %></a>
      <span class="lighterSmall"> at </span><%= job.company %>
    </li>
  <% end %>
</ul>
<% else %>
<div class="info">Nothing to be found for your searched criteria.</div>
<ul>
  <li>Look for typos in the searched word(s) and, if found, correct them.</li>
  <li>Be less specific. Try "web designer" instead of "senior web designer".</li>
  <li>Try similar words. If "designer" doesn\'t return anything, try "design".</li>
</ul>
<% end %>

app/views/search/_joobsbox_index.html.erb
<div class="span8">
<div class="page-header">
  <h1>Search : <%= params[:jobq] %></h1>
</div>

<% if !@jobs.blank? %>
<% i =0  %>
  <table class="table table-bordered table-striped table-hover" style="font-size:16px;">
    <thead>
      <tr>
        <th>#</th>
        <th colspan="3">Job at Company in Location</th>
      </tr>
    </thead>
    <tbody>
       <% @jobs.each do |job |%>
       <% i = i+1 %>
      <tr>
        <td><%= i %></td>
        <td colspan="3">
      <a href="<%=job_path(job)%>"><%= job.title %></a>
      <span class="lighterSmall" style="color: #93E08B;"> at </span><%= job.company %>
      <span class="lighterSmall" style="color: #93E08B;"> in </span><%= job.location %>
      </td>
      </tr>
        <% end %>
    </tbody>
  </table>
<% else %>
<div class="info">Nothing to be found for your searched criteria.</div>
<ul>
  <li>Look for typos in the searched word(s) and, if found, correct them.</li>
  <li>Be less specific. Try "web designer" instead of "senior web designer".</li>
  <li>Try similar words. If "designer" doesn\'t return anything, try "design".</li>
</ul>
<% end %>
</div>

app/views/search/google_images.html.erb
<div class="span8">
<% for image in @google_images %>
<div style ="width:148px; height: 120px;float:left;">
 <%= link_to(image_tag(image.thumbnail, :style => 'padding:3px; border:solid 1px #EEE; margin:2px; width:100px; height:100px;float:left'), image.original) %>
  <span><%= image.width %>x<%= image.height %></span>
</div>
<% end %>
<%#= clear %>
<%= link_to_unless (params[:start] == 0), 'Prev',  { :start => (params[:start] - 8) , :keywords => params[:keywords] } %> |
<%= link_to_unless (params[:start] > 0 && @google_images.blank?), 'Next', { :start => (params[:start] + 8) ,  :keywords => params[:keywords] } %>

</div>

app/views/search/index.html.erb
<div class="list">
   <%= render("#{session[:theme]}_index") %>
</div>

app/views/search/search.html.erb
<div class="span8">
<div class="page-header">
  <h1>Search : <%= params[:resumeq] %></h1>
</div>

<% if !@resumes.blank? %>
<% i =0  %>
  <table class="table table-bordered table-striped table-hover" style="font-size:16px;">
    <thead>
      <tr>
        <th>#</th>
        <th colspan="3">Profiles</th>
      </tr>
    </thead>
    <tbody>
       <% @resumes.each do |prof |%>
       <% i = i+1 %>
      <tr>
        <td><%= i %></td>
        <td colspan="3"><a href="<%= profile_path(prof.user,prof) %>"><%= prof.resume_title %></a></td>
      </tr>
        <% end %>
    </tbody>
  </table>
<% else %>
<div class="info">Nothing to be found for your searched criteria.</div>
<ul>
  <li>Look for typos in the searched word(s) and, if found, correct them.</li>
  <li>Be less specific. Try "web designer" instead of "senior web designer".</li>
  <li>Try similar words. If "designer" doesn\'t return anything, try "design".</li>
</ul>
<% end %>
</div>