config/routes.rb
JoobsboxRails::Application.routes.draw do

 

  devise_for :users, :controllers => {:sessions => 'sessions'}

  namespace :admin do  
    match '' => 'home#index'
    resources :categories, :postings, :settings , :themes , :plugins , :roles , :users ,
              :group_permissions 
    resources :groups do
      member do
        get "users"
        post "add_users"
        post "remove_users"
      end
    end
  end

  match 'publish' => 'jobs#new'
  match 'post' => 'resumes#new'
  match 'search' => 'search#index'
  match 'google_images' => 'search#google_images'
  match 'profiles' => 'search#search'
  match ':user_id/profile/:id' => 'resumes#profile' , :as => :profile
  resources :jobs do
    member do
       get 'applied_resumes'
    end
    collection do
      get 'my_postings'     
    end
  end
  resources :resumes do
    member do
      get 'apply'
      get 'download'
    end
    collection do
      post 'submit_profile'
    end
  end
  resources :categories

  root :to => 'home#index'

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_default_index.html.erb
<% Category.all.each do |cat| %>
  <% if cat.approved_jobs.count > 0 %>
    <div class="inner">
      <div class="toRight">        
        <%= link_to "RSS FEED", category_path(cat,:format => "rss") %>
      </div>
      <a class="category-link" href="<%=  category_path(cat) %>">
        <%=cat.name%>			</a>
    </div>
    <ul>
      <% cat.approved_jobs.limit(Setting.first.jobs_per_cat || 10).each_with_index do |job , i |%>
        <li <% if i%2 == 0 %> class="alternate"<% end%>  >
          <strong><%= job.location %> :</strong>
          <a href="<%=job_path(job)%>"><%= job.title %></a>
          <span class="lighterSmall"> at </span><%= job.company %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/home/_joobsbox_index.html.erb
  <% Category.all.each do |cat| %>
  <% if cat.approved_jobs.count > 0 %>
  <div class="inner">
    <div class="toRight">
      <%= link_to "RSS", category_path(cat,:format => "rss") %>
      <%= link_to image_tag("joobsbox/icon-rss.gif" , :alt => "RSS"), category_path(cat,:format => "rss") %>
      
    </div>
    <a href="<%=  category_path(cat) %>"><%=cat.name%></a>
  </div>
  <ul>
    <% cat.approved_jobs.limit(Setting.first.jobs_per_cat || 10).each_with_index do |job , i |%>
    <li <% if i%2 == 0 %> class="alternate"<% end%>  >
      <a href="<%=job_path(job)%>"><%= job.title %></a>
      <span class="lighterSmall"> at </span><%= job.company %>
      <span class="lighterSmall"> in </span><%= job.location %>
    </li>
    <% end %>
  </ul>
  <% end %>
  <% end %>  

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>Your, career!</h1>
  <p>This is the most flexible open source job board application.</p>
  <!--<p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p> -->
  <p>   

       <form action="/search" method="get" class="navbar-search pull-right" style="float:none;">
        <input name="jobq" type="text" id="searchInput" placeholder="Search for job" style="width: 444px;" class="search-query span2" />
        <button type="submit" class="btn btn-success" style="margin-top: 0px;">Search</button>
      </form>

    <% if  (user_signed_in? && (current_user.has_role?(:recruiter) || current_user.has_role?(:employer) || current_user.has_role?(:admin))) %>
       <form action="/profiles" method="get" class="navbar-search pull-right" style="float:none;">
        <input name="resumeq" type="text" id="searchInput" placeholder="Search for profile" style="width: 444px;" class="search-query span2" />
        <button type="submit" class="btn btn-success" style="margin-top: 0px;">Search</button>
      </form>
  <% end %>
</p>
</div>
<!-- Main hero unit for a primary marketing message or call to action -->
<!-- Example row of columns -->
<div class="row-fluid">
  <% if (user_signed_in? && current_user.has_role?(:jobseeker)) %>
  <div class="span8">
    <h2>Post a Resume</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-success" href="/post">Submit</a></p>
  </div>
  <div class="span4">
    <h2>Ads</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  </div>
  <% elsif (user_signed_in? && (current_user.has_role?(:employer) || current_user.has_role?(:admin))) %>
  <div class="span8">
    <h2>Post a job for 30 days</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-success" href="/publish">Post</a></p>
  </div>
  <div class="span4">
    <h2>Ads</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  </div>
  <% elsif  (user_signed_in? && current_user.has_role?(:recruiter)) %>
   <div class="span4">
    <h2>Post a Resume</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-success " href="/post">Submit</a></p>
   </div>
   <div class="span4">
    <h2>Post a job for 30 days</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-success " href="/publish">Post</a></p>
  </div>
   <div class="span4">
    <h2>Ads</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  </div>
  <% else %>
   <div class="span8">
    <h2>Post a Resume</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-success " href="/post">Submit</a></p>
  </div>
 <div class="span4">
    <h2>Post a job for 30 days</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-success " href="/publish">Post</a></p>
  </div>
  <% end %>
</div>