config/routes.rb
JoobsboxRails::Application.routes.draw do

 

  devise_for :users, :controllers => {:sessions => 'sessions'}

  namespace :admin do  
    match '' => 'home#index'
    resources :categories, :postings, :settings , :themes , :plugins , :roles , :users ,
              :group_permissions 
    resources :groups do
      member do
        get "users"
        post "add_users"
        post "remove_users"
      end
    end
  end

  match 'publish' => 'jobs#new'
  match 'post' => 'resumes#new'
  match 'search' => 'search#index'
  match 'google_images' => 'search#google_images'
  match 'profiles' => 'search#search'
  match ':user_id/profile/:id' => 'resumes#profile' , :as => :profile
  resources :jobs do
    member do
       get 'applied_resumes'
    end
    collection do
      get 'my_postings'     
    end
  end
  resources :resumes do
    member do
      get 'apply'
      get 'download'
    end
    collection do
      post 'submit_profile'
    end
  end
  resources :categories

  root :to => 'home#index'

end

app/controllers/admin/postings_controller.rb
class Admin::PostingsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!

  def create
    if params[:job]
       if params[:actionPending] == "accept"
          Job.update_all("is_approved = 1", "id in (#{params[:job].join(',')})" )
          Job.solr_reindex
          Sunspot.commit
       else
          Job.delete_all("id in (#{params[:job].join(',')})")
       end
      render :text => "The operation has finished successfully."
    else
      render :text => "Please select the postings to accept or delete."
    end  
  end
end

app/helpers/admin/postings_helper.rb
module Admin::PostingsHelper
end

app/views/admin/postings/index.html.erb
<h1 class="dashboard-title">Postings</h1>
<div id="pending" class="postings-container">
  <h2>Pending postings</h2>
  <form action="/admin/postings" method="post" id="form-pending">
    <div id="toolbar">
  		Actions:  		<a id="acceptPostingsPending" class="accept">Accept selected postings</a>
      <a id="deletePostingsPending" class="delete">Delete selected postings</a>
    </div>
    <table id="pending-postings" class="postings">
      <thead>
        <tr>
          <th></th>
          <th><input id="selectAllPending" type="checkbox"/></th>
          <th>Title</th>
          <th>Company</th>
          <th>Location</th>
          <th>Posted at</th>
        </tr>
      </thead>
      <tbody>
        <% Job.pending_postings.each do |job| %>
          <tr id="job_<%= job.id %>" class="job">
            <td class="operations"><a class="expand" href="#">+</a><a href="<%= edit_job_path(job) %>" class="editBtn"></a></td>
            <td><input name="job[]" type="checkbox" value="<%= job.id %>"/></td>
            <td><%= job.title %></td>
            <td><%= job.company %></td>
            <td><%= job.location %></td>
            <td><%= job.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
          </tr>
          <tr class="next">
            <td colspan="6"><%= job.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <input id="actionPending" name="action" value="approve" type="hidden"/>
  </form>

</div>
<div id="approved" class="postings-container">
  <h2>Active postings</h2>

    <form action="/admin/postings" method="post" id="form-approved">
      <div id="toolbar">
                  Actions:		<a id="deletePostingsApproved" class="delete">Delete selected postings</a>
      </div>
      <table id="approved-postings" class="postings">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th>Title</th>
            <th>Company</th>
            <th>Location</th>
            <th>Posted at</th>
          </tr>
        </thead>
        <tbody>
          <% Job.total_postings.each do |job| %>
            <tr id="job_<%= job.id %>" class="job">
              <td class="operations"><a class="expand" href="#">+</a><a href="<%= edit_job_path(job) %>" class="editBtn"></a></td>
              <td><input name="job[]" type="checkbox" value="<%= job.id %>"/></td>
              <td><%= job.title %></td>
              <td><%= job.company %></td>
              <td><%= job.location %></td>
              <td><%= job.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            </tr>
            <tr class="next">
              <td colspan="6"><%= job.description %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <input id="actionApproved" name="action" value="delete" type="hidden"/>
    </form> 
</div>
<div id="operationDialog">
	The operation has finished successfully.
</div>

<div id="dialog-confirm" title="You want to delete the selected postings?" style="display: none;">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>These items will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>

<%= stylesheet_link_tag    "admin/postings/postings.css", :media => "screen" %>
<%= stylesheet_link_tag    "js/lib/jquery-ui/css/cupertino/jquery-ui-1.7.1.custom.css", :media => "screen" %>


<%= javascript_include_tag "admin/postings/jquery.json-1.3.min.js" %>
<%= javascript_include_tag "admin/postings/postings.js" %>
<%= javascript_include_tag "js/lib/jquery-ui/js/jquery-ui-1.7.custom.min.js" %>