config/routes.rb
JoobsboxRails::Application.routes.draw do

 

  devise_for :users, :controllers => {:sessions => 'sessions'}

  namespace :admin do  
    match '' => 'home#index'
    resources :categories, :postings, :settings , :themes , :plugins , :roles , :users ,
              :group_permissions 
    resources :groups do
      member do
        get "users"
        post "add_users"
        post "remove_users"
      end
    end
  end

  match 'publish' => 'jobs#new'
  match 'post' => 'resumes#new'
  match 'search' => 'search#index'
  match 'google_images' => 'search#google_images'
  match 'profiles' => 'search#search'
  match ':user_id/profile/:id' => 'resumes#profile' , :as => :profile
  resources :jobs do
    member do
       get 'applied_resumes'
    end
    collection do
      get 'my_postings'     
    end
  end
  resources :resumes do
    member do
      get 'apply'
      get 'download'
    end
    collection do
      post 'submit_profile'
    end
  end
  resources :categories

  root :to => 'home#index'

end

app/models/resume.rb
class Resume < ActiveRecord::Base
   attr_accessible :nationality, :current_location,:mobile_number,:landline,:gender,:user_id,
                   :total_experience_yrs , :total_experience_mns , :current_industry ,:key_skills,
                   :resume_title , :attachment, :content_type , :filename

  belongs_to :user

  mount_uploader :attachment, AttachmentUploader

  validates :nationality, :current_location,:gender,:user_id,:resume_title , :attachment,
                   :total_experience_yrs , :total_experience_mns , :current_industry ,
                   :key_skills, :presence => true

  validates :mobile_number, :presence => {:message => "mobile or landline required" , :if => Proc.new {|resume| resume.landline.blank? }}
  validates :landline, :presence => {:message => "mobile or landline required", :if => Proc.new {|resume| resume.mobile_number.blank?}}
  
  validates :landline, :format => { :with => /^\d{10}$/, :allow_blank => true}
  validates :mobile_number, :format => { :with => /^[1-9]\d{9}$/, :allow_blank => true}



  INDUSTRIES = ["Automotive/ Ancillaries","Banking/ Financial Services","Bio Technology & Life Sciences",
 "Chemicals/ Plastic/ Rubber","Construction","Consumer Goods/ FMCG","Education",
 "Entertainment/ Media/ Publishing","Insurance","ITES/ BPO/ KPO","IT/ Computers - Hardware",
 "IT/ Computers - Software","Machinery/ Equipment Mfg","Oil/ Gas/ Petroleum","Pharmaceuticals",
 "Power","Real Estate","Retailing","Telecom","Advertising","Agriculture/ Dairy Based",
 "Airlines","Beauty/Fitness/PersonalCare/SPA","Beverages/ Liquor","Cement","Consultancy",
 "Courier/ Freight/ Transportation","Dotcom","E-Learning","Engineering, Procurement, Construction",
 "Facility management","Fertilizer/ Pesticides","Food & Packaged Food","Textiles / Yarn / Fabrics / Garments",
 "Gems & Jewellery","Government/ PSU/ Defence","Home Appliances (TV, Fridge, AC etc.)",
 "Hospitals/ Health Care","Hotels/ Restaurant","Import / Export","Iron/ Steel","ISP","Leather",
 "Market Research","Medical Transcription","Mining","NGO","Non-Ferrous Metals (Aluminium, Zinc etc.)",
 "Office Equipment","Paints","Paper","Printing/ Packaging","Public Relations (PR)","Semiconductor",
 "Shipping","Social Media","Sugar","Travel/ Tourism","Tyres","Wood","Other","Any"]

  def self.nationalities
    nationality = YAML.load_file("#{Rails.root}/config/nationality.yml")
    nationality["nationality"]["countries"]
  end

  def self.current_loactions
    locations = YAML.load_file("#{Rails.root}/config/currentlocation.yml")
    locations["locations"]
  end



  before_save :update_attachment_attributes

#   searchable do
#    text :resume_title , :key_skills
#    time    :created_at
#    integer :user_id
#    attachment :document_attachment
#  end

  
  def document_attachment
	    "#{Rails.root}/public/#{attachment.url}"
  end
  private

  def update_attachment_attributes
    if attachment.present? && attachment_changed?
      self.content_type = attachment.file.content_type
      self.filename = attachment.file.original_filename
    end
  end

end

#
#+----------------------+--------------+------+-----+---------+----------------+
#| Field                | Type         | Null | Key | Default | Extra          |
#+----------------------+--------------+------+-----+---------+----------------+
#| id                   | int(11)      | NO   | PRI | NULL    | auto_increment |
#| nationality          | varchar(255) | YES  |     | NULL    |                |
#| current_location     | varchar(255) | YES  |     | NULL    |                |
#| mobile_number        | varchar(255) | YES  |     | NULL    |                |
#| landline             | varchar(255) | YES  |     | NULL    |                |
#| gender               | varchar(255) | YES  |     | NULL    |                |
#| user_id              | int(11)      | YES  |     | NULL    |                |
#| total_experience_yrs | int(11)      | YES  |     | NULL    |                |
#| total_experience_mns | int(11)      | YES  |     | NULL    |                |
#| current_industry     | varchar(255) | YES  |     | NULL    |                |
#| function             | varchar(255) | YES  |     | NULL    |                |
#| key_skills           | varchar(255) | YES  |     | NULL    |                |
#| resume_title         | varchar(255) | YES  |     | NULL    |                |
#| attachment           | varchar(255) | YES  |     | NULL    |                |
#| created_at           | datetime     | NO   |     | NULL    |                |
#| updated_at           | datetime     | NO   |     | NULL    |                |
#+----------------------+--------------+------+-----+---------+----------------+

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  layout 'jobseeker'

  def index
    @resumes = current_user.resumes
  end

  def new
    @resume = Resume.new
    groups = current_user.groups    
    if !groups.blank?
      current_user.can_create?(groups,"Resume")
    else
      authorize! :create, @resume, :message => 'Not authorized as an jobseeker.'
    end    
  end

  def create
    @resume = Resume.new(params[:resume])
    respond_to do |format|
      if @resume.save
        format.html { redirect_to resumes_path, notice: 'The Resume has been Submitted.Thank you for submitting .' }
        format.json { render json: @resume, status: :created, location: @resume }
      else
        format.html { render action: "new" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
    @resume = Resume.find(params[:id])
  end

  def update
    @resume = Resume.find(params[:id])
    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to @resume, notice: 'The Resume has been Updated Successfully .' }
        format.json { render json: @resume, status: :created, location: @resume }
      else
        format.html { render action: "update" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
  
    #require 'yomu'
    
    @resume = Resume.find(params[:id])
    if @resume.user != current_user
    groups = current_user.groups
    if !groups.blank?
      current_user.can_read?(groups,"Resume")
    else
      authorize! :read, @resume, :message => 'Not authorized as an jobseeker.'
    end
    end

 
   @path = "#{@resume.attachment.url}"

#    yomu = Yomu.new("#{Rails.root}/public#{@resume.attachment.url}")
#
#    @doc2 = yomu.text

    
   
    #render :file => "#{Rails.root}/public#{@resume.attachment.url}", :content_type =>  @resume.content_type

#    send_file "#{Rails.root}/public#{@resume.attachment.url}",
#            :filename => @resume.filename ,
#            :type => @resume.content_type,
#            :disposition => 'attachment'
  end


  def download
    @resume = Resume.find(params[:id])
    if @resume.user != current_user
    groups = current_user.groups
    if !groups.blank?
      current_user.can_read?(groups,"Resume")
    else
      authorize! :read, @resume, :message => 'Not authorized as an jobseeker.'
    end
    end

    send_file "#{Rails.root}/public#{@resume.attachment.url}",
            :filename => @resume.filename ,
            :type => @resume.content_type,
           :disposition => 'attachment'
  end

  def destroy
    @resume = current_user.resumes.find(params[:id])
    groups = current_user.groups
    if !groups.blank?
      current_user.can_delete?(groups,"Resume")
    else
      authorize! :destroy, @resume, :message => 'Not authorized as an jobseeker.'
    end

    if @resume.destroy
      flash[:notice] = "Resume was deleted."
      redirect_to resumes_url
    end
  end

  def apply
    @job = Job.find(params[:id])
    @applied_resume = AppliedResume.new
  end

  def submit_profile
    @job = Job.find(params[:applied_resume][:job_id])
    @applied_resume = AppliedResume.new(params[:applied_resume])
    @applied_resume.applied_date = Date.today
    respond_to do |format|
      if @applied_resume.save
        format.html { redirect_to jobs_path, notice: 'The Resume has been Submitted.Thank you for submitting .' }
        format.json { render json: @applied_resume, status: :created, location: @applied_resume }
      else
        format.html { render action: "apply" }
        format.json { render json: @applied_resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def profile
    @resume = Resume.find(params[:id])
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/apply.html.erb
<div class="span8">
  <div class="page-header">
    <h1>Submit your profile</h1>
  </div>
  <%= stylesheet_link_tag    "joobsbox/publishForm.css", :media => "all" %>
   <fieldset>
<%= simple_form_for(@applied_resume , :url => submit_profile_resumes_path, :html => {:id => "formPublish" , :class=>"form-horizontal well" , :style => "text-align:left;"}) do |f| %>
 <%= f.error_notification %>
 <div class="control-group" >
    <%= f.input :resume_id ,:input_html => {:class => "fields"},  :collection =>  current_user.resumes.collect{ |u| [u.resume_title, u.id] }, :prompt => "Choose...",:label_html => { :class => 'text-fields' }, :required => true %>
 </div>
 <div class="control-group" >
    <%= f.input :covering_letter, :input_html => {:class => "fields" , :rows => "15" , :cols => "80" ,:style => "width: 575px;"}, :label_html => { :class => 'text-fields' } %>
 </div>
 <div class="control-group" >
  <%= f.input :job_id,:as => :hidden , :input_html => {:value => @job.id} %>
 </div>
 <div class="form-actions">
    <%= f.submit "Apply", :class => "btn btn-primary btn-large" , :style => " margin-left: 281px;padding-left: 50px;padding-right: 50px;"  %>
 </div>
<% end %>
</fieldset>
</div>

app/views/resumes/edit.html.erb
<%#= stylesheet_link_tag    "joobsbox/publishForm.css", :media => "all" %>
<div class="span8">
<div class="page-header">
  <h1>Update a Resume</h1>
</div>


<%= simple_form_for(@resume , :html => { :class=>"form-horizontal" , :multipart => true}) do |f| %>

     <%= f.error_notification %>
<fieldset>
    <legend>Personal Details </legend>
    <hr/>
    <div class="control-group">
    <%= f.input :nationality ,:input_html => {:class => "controls"}, :label_html => {:class => "control-label"}, :collection =>  Resume.nationalities, :prompt => "Choose...", :required => true, :autofocus => true %>

    </div><div class="control-group">
      <%= f.input :current_location, :input_html => {:class => "controls"},:label_html => {:class => "control-label"}, :required => true , :collection => Resume.current_loactions, :prompt => "Choose..." %>

    </div><div class="control-group">
  <%= f.input :mobile_number ,:input_html => {:class => "controls"},:label_html => {:class => "control-label"}, :required => false %>
    </div>
    <div class="control-group"><label class="control-label"></label><div class = "controls">Or</div></div>
   <div class="control-group">
  <%= f.input :landline, :input_html => {:class => "controls"}, :label_html => {:class => "control-label"}, :required => false %>
    </div>
    <div class="control-group">
  <%= f.input :gender,:collection =>['Male','Female'], :as => :radio_buttons, :label_html => {:class => "control-label"},:input_html => {:class => "controls"}, :required => true %>
    </div>
</fieldset>

<fieldset>
    <legend>Professional Details </legend>
<hr/>
     <div class="control-group">
    <label class = "control-label">Total experience</label>
    <%= f.input :total_experience_yrs,:label => false,  :prompt => "Years",:collection => 1..50 , :required => true ,:input_html => {:style => "float: left;margin-left: 210px;margin-right: 15px;width: 104px;" , :class => "controls" } , :error_html => { :class => 'year_error'}%>
    <%= f.input :total_experience_mns,:label => false, :prompt => "Months", :collection => 0..11 , :input_html => {:class => "fields",:style => "margin-left: -175px;width: 100px;" },  :required => true , :error_html => { :class => 'month_error'} %>
     </div> <div class="control-group">
  <%= f.input :current_industry, :collection => Resume::INDUSTRIES , :input_html => {:class => "controls"},:label_html => {:class => "control-label"},  :required => true %>
  </div> <div class="control-group">
  <%= f.input :key_skills, :input_html => {:class => "controls"},:label_html => {:class => "control-label"},  :required => true %>
  </div>
</fieldset>

  <fieldset>
    <legend>Resume Details </legend>
    <hr/>
     <div class="control-group">
    <%= f.input :resume_title, :input_html => {:class => "controls"}, :label_html => {:class => "control-label"}, :required => true %>
  </div> <div class="control-group">
  <%= f.input :attachment, :as => :file, :input_html => {:class => "controls"}, :label_html => {:class => "control-label"}, :required => true %>
  </div>
  </fieldset>
   <div class="control-group">
    By Clicking the submit button, you are agree to Career Hub privacy statement and terms of use
    <%= f.input :user_id,:as => :hidden , :input_html => {:value => current_user.id} %>
  </div>
 <div class="control-group">
<%= link_to 'back', resumes_path  , :class => "btn btn-success" %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <%= f.submit "Update" , :class => "btn btn-primary" %>
    
 </div>

<% end %>
</div>


<style type="text/css">
  .collection_radio_buttons {
    float: left;
    margin-top: 3px;
    padding-left: 5px;
  }

  .radio input[type="radio"], .checkbox input[type="checkbox"] {
    float: left;
    margin-left: 207px;
  }

  .error{
   color: #B94A48;;
    float: right;
    margin-top: 9px;
    width: 76%;
}
.form-horizontal .controls {
    margin-left: 30px;
}

.year_error{
    float: left;
    margin-left: 297px;
    width: 32%;
}
.month_error{
    margin-left: 12px;
    margin-top: -17px;
    text-align: left;
    width: 36%;
}
#resume_gender_female{
  margin-left: 5px;
}
</style>

app/views/resumes/index.html.erb
<div class="span8">
  <div class="page-header"><h1>Resumes</h1></div>
<table class="table table-bordered table-striped table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>Skills</th>
    <th>Resume Title</th>
   
    <th>Status</th>
    <th colspan="4" style="text-align: center;">Action</th>
  </tr>
  </thead>
  <tbody>
    <% @resumes.each_with_index do |rs,i| %>
    <tr>
      <td><%= i + 1  %></td>
      <td><%= rs.key_skills %></td>
      <td><%= rs.resume_title %></td>     
      <td><%= rs.status ? "Active" : "Inactive" %></td>
       <td><%= link_to 'View' , rs , :class => "btn btn-success" if !rs.attachment.blank? %></td>
       <td><%= link_to 'Edit' , edit_resume_path(rs) , :class => "btn btn-success" if !rs.attachment.blank? %></td>
      <td><%= link_to 'Download' , download_resume_path(rs) , :class => "btn btn-success " if !rs.attachment.blank? %> </td>
      <td>
        <%=  button_to  "Delete", {:action => 'destroy' , :id =>rs.id},  :confirm => "Are you sure you want to delete this resume", :method => :delete , :class => "btn btn-danger" if can? :destroy, rs %>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>
</div>

app/views/resumes/new.html.erb
<%#= stylesheet_link_tag    "joobsbox/publishForm.css", :media => "all" %>
<div class="span8">
<div class="page-header">
  <h1>Post a Resume</h1>
</div>


<%= simple_form_for(@resume , :html => { :class=>"form-horizontal" , :multipart => true}) do |f| %>

     <%= f.error_notification %>
<fieldset>
    <legend>Personal Details </legend>
    <hr/>
    <div class="control-group">
    <%= f.input :nationality ,:input_html => {:class => "controls"}, :label_html => {:class => "control-label"}, :collection =>  Resume.nationalities, :prompt => "Choose...", :required => true, :autofocus => true %>
    
    </div><div class="control-group">
      <%= f.input :current_location, :input_html => {:class => "controls"},:label_html => {:class => "control-label"}, :required => true , :collection => Resume.current_loactions, :prompt => "Choose..." %>
    
    </div><div class="control-group">
  <%= f.input :mobile_number ,:input_html => {:class => "controls"},:label_html => {:class => "control-label"}, :required => false %>
    </div>
    <div class="control-group"><label class="control-label"></label><div class = "controls">Or</div></div>
   <div class="control-group">
  <%= f.input :landline, :input_html => {:class => "controls"}, :label_html => {:class => "control-label"}, :required => false %>
    </div>
    <div class="control-group">
  <%= f.input :gender,:collection =>['Male','Female'], :as => :radio_buttons, :label_html => {:class => "control-label"},:input_html => {:class => "controls"}, :required => true %>
    </div>
</fieldset>

<fieldset>
    <legend>Professional Details </legend>
<hr/>
     <div class="control-group">
    <label class = "control-label">Total experience</label>
    <%= f.input :total_experience_yrs,:label => false,  :prompt => "Years",:collection => 1..50 , :required => true ,:input_html => {:style => "float: left;margin-left: 210px;margin-right: 15px;width: 104px;" , :class => "controls" } , :error_html => { :class => 'year_error'}%>
    <%= f.input :total_experience_mns,:label => false, :prompt => "Months", :collection => 0..11 , :input_html => {:class => "fields",:style => "margin-left: -175px;width: 100px;" },  :required => true , :error_html => { :class => 'month_error'} %>
     </div> <div class="control-group">
  <%= f.input :current_industry, :collection => Resume::INDUSTRIES , :input_html => {:class => "controls"},:label_html => {:class => "control-label"},  :required => true %>
  </div> <div class="control-group">
  <%= f.input :key_skills, :input_html => {:class => "controls"},:label_html => {:class => "control-label"},  :required => true %>
  </div>
</fieldset>

  <fieldset>
    <legend>Resume Details </legend>
    <hr/>
     <div class="control-group">
    <%= f.input :resume_title, :input_html => {:class => "controls"}, :label_html => {:class => "control-label"}, :required => true %>
  </div> <div class="control-group">
  <%= f.input :attachment, :as => :file, :input_html => {:class => "controls"}, :label_html => {:class => "control-label"}, :required => true %>
  </div>
  </fieldset>
   <div class="control-group">
    By Clicking the submit button, you are agree to Career Hub privacy statement and terms of use
    <%= f.input :user_id,:as => :hidden , :input_html => {:value => current_user.id} %>
  </div>
 <div class="control-group">
    <%= f.submit "Submit" , :class => "btn btn-primary" %>
 </div>

<% end %>
</div>


<style type="text/css">
  .collection_radio_buttons {
    float: left;
    margin-top: 3px;
    padding-left: 5px;
  }

  .radio input[type="radio"], .checkbox input[type="checkbox"] {
    float: left;
    margin-left: 207px;
  }

  .error{
   color: #B94A48;;
    float: right;
    margin-top: 9px;
    width: 76%;
}
.form-horizontal .controls {
    margin-left: 30px;
}

.year_error{
    float: left;
    margin-left: 297px;
    width: 32%;
}
.month_error{
    margin-left: 12px;
    margin-top: -17px;
    text-align: left;
    width: 36%;
}
#resume_gender_female{
  margin-left: 5px;
}
</style>

app/views/resumes/profile.html.erb
<div class="span8">
<div class="page-header">
  <h1><%= @resume.user.name %></h1>
</div>
  <table class="table table-bordered table-striped table-hover" style="font-size:16px;">
    <thead>
      <tr>
        <th>Resume Headline</th>
        <th colspan="3"><%= @resume.resume_title  %> </th>
      </tr>
    </thead>
    <tbody>    
      <tr>
        <td>Industry</td>
        <td colspan="3"><%=@resume.current_industry %></td>
      </tr>
      <tr>
        <td>Experience</td>
        <td colspan="3"><%= @resume.total_experience_yrs %> Year(s) <%= @resume.total_experience_mns %> Month (s)</td>
      </tr>
      <tr>
        <td>Location</td>
        <td colspan="3"><%=@resume.current_location %></td>
      </tr>
       <tr>
        <td>Key Skills</td>
        <td colspan="3"><%=@resume.key_skills %></td>
      </tr>
       <tr>
        <td>Resume</td>
        <td colspan="3"><%= link_to 'Download' , download_resume_path(@resume) , :class => "btn btn-success " %> </td>
      </tr>
    </tbody>
  </table>
  <div class="page-header">
  <h2>Recruiters will reach you at </h2>
  </div>
  <div class="well">
    <i class="icon-envelope"></i> <%=  @resume.user.email %>
    <i class="icon-bell"></i> <%=  @resume.mobile_number || @resume.landline %>
  </div>
</div>

app/views/resumes/show.html.erb
<div class="span8">
  <iframe style="border-style: none;" src="http://docs.google.com/viewer?url=<%=request.env['HTTP_HOST'] + @path%>&embedded=true" height="830" width="750"></iframe>
  

</div>